# YAML alias
default: &common_settings
  database:
    name: 'esc_dev'

development:
  <<: *common_settings
test:
  <<: *common_settings

production:
  <<: *common_settings
  database:
    name: 'esc'
