# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
color: true
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - ts
# fgrep and grep are mutually exclusive
# fgrep: something
# file:
#   - /path/to/some/file
#   - /path/to/some/other/file
forbid-only: false
forbid-pending: false
full-trace: false
# global:
#   - jQuery
#   - $
# fgrep and grep are mutually exclusive
# grep: something
# growl: false
# ignore:
#   - /path/to/some/ignored/file
# inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
recursive: false
reporter: spec
# reporter-option:
#   - foo=bar
#   - baz=quux
require: 'ts-node/register/transpile-only'
retries: 1
# slow: 75
sort: false
timeout: false # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
# v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
# spec: src/**/*.spec.ts # the positional arguments!
# ui: bdd
watch: true
watch-files:
  - 'src/**/*.ts'
  - 'test/**.ts'
# watch-ignore:
#   - 'lib/vendor'